Update IRC information.
xiph/rav1e pull request #2744
Opened 2021-05-26 04:28 UTC by tdaede

I'm not sure what to use for webchat, it seems that Libera.Chat
doesn't run a webchat yet.

2021-05-26 05:09 UTC, barrbrain commented
We could include a link to https://libera.chat/ for more information about the network. Their IRC client guide lists https://kiwiirc.com/ as an available web client.

2021-05-26 05:19 UTC, lu-zero approved these changes
I second what @barrbrain suggested.

2021-05-26 06:13 UTC, barrbrain approved these changes

2021-05-26 06:13 UTC, negge commented
There has been no public discussion of moving servers. I think this PR is premature.

2021-05-26 06:14 UTC, negge requested changes
There has been no public discussion of moving servers. I think this PR is premature.

2021-05-26 06:17 UTC, barrbrain commented
For the record, I approve of the content of this change and agree that merging it should be gated on the outcome of public discussion.

2021-05-26 11:38 UTC, vibhoothiiaanand reviewed
If moving is going to happen, we can hyperlink the kiwiric chat link like how we did with freenode,

2021-05-26 11:38 UTC, vibhoothiiaanand commented on README.md
> +Come chat with us on the IRC channel #daala on [Libera.Chat](https://libera.chat/)! You can also use https://kiwiirc.com/ to join with a web browser.
```suggestion
Come chat with us on the IRC channel #daala on [Libera.Chat](https://libera.chat/)! You can also use https://kiwiirc.com/ to join with a [web browser](https://kiwiirc.com/nextclient/#ircs://irc.libera.chat/#daala).
```

2021-05-26 15:13 UTC, barrbrain commented on README.md
> +Come chat with us on the IRC channel #daala on [Libera.Chat](https://libera.chat/)! You can also use https://kiwiirc.com/ to join with a web browser.
Plain URLs like  https://kiwiirc.com/ are automatically linkified.

2021-05-28 20:35 UTC, negge reviewed
Please add instructions for matrix users

2021-05-30 13:09 UTC, negge requested changes

2021-05-30 13:09 UTC, negge commented on README.md
> +Come chat with us on the IRC channel #daala on [Libera.Chat](https://libera.chat/)! You can also use [web browser](https://kiwiirc.com/nextclient/#ircs://irc.libera.chat/#daala) to join with a web br
Can we use this link instead?

https://web.libera.chat/?channel=#daala

2021-05-31 17:12 UTC, tmatth approved these changes

2021-05-31 22:16 UTC, negge approved these changes
LGTM

2021-06-08 19:04 UTC, vibhoothi commented
@tdaede can we land this

2021-06-25 08:31 UTC, barrbrain commented on README.md
> +Come chat with us on the IRC channel #daala on [Libera.Chat](https://libera.chat/)! You can also use [web browser](https://web.libera.chat/?channel=#daala) to join with a web browser.
```suggestion
Come chat with us on the IRC channel #daala on [Libera.Chat](https://libera.chat/)! You can also use a [web client](https://web.libera.chat/?channel=#daala) to join with a web browser.
```

2021-07-07 14:47 UTC, merged