Refactor the SpeedSettings struct and impl
xiph/rav1e pull request #2855
Opened 2021-12-10 04:03 UTC by shssoichiro

The impetus for this change is that the documentation for speed
settings, being a manually-maintained comment, would easily become out
of date and was difficult to maintain. The primary change this
introduces is that, rather than having a separate function for each
speed setting to determine when to enable it, the `from_preset` function
now sets all settings per speed level, with the `default()` being speed
0, and overriding as the speed increases. The idea is that this will
make it much easier to see which features are enabled at which speed
levels.

This also consolidates a couple of fields which were redundant, namely:
- `no_scene_detection` and `fast_scene_detection` are now one setting
  called `scene_detection_mode`
- `rdo_lookahead_frames` existed both on EncoderConfig and
  EncoderConfig.SpeedSettings. It has been removed from EncoderConfig
  itself, as even though it can be overridden by a CLI arg, it is
  primarily controlled by the speed preset.

2021-12-10 04:31 UTC, shssoichiro commented
The build failures seem to be unrelated to this PR:

```
libaom0_1.0.0.errata1.ds-1_amd64.deb: FAILED
sha256sum: WARNING: 1 computed checksum did NOT match
```

2021-12-10 07:53 UTC, lu-zero requested changes
Could you please split the moving of rdo_lookahead_frames from the rest and the same for removing no_scene_detection?

Beside that I'm fine with the changes, @barrbrain I'd like your opinion as well.

While at it, mark the struct non_exhaustive please.

2021-12-10 13:45 UTC, shssoichiro commented
I'm assuming separate commits within this PR is fine? If so, I'll get that pushed up here this morning.

2021-12-10 13:56 UTC, lu-zero commented
It is fine, we have to update the debs again meanwhile :)

Thank you !

2021-12-11 14:24 UTC, shssoichiro commented
All requested changes have been applied and rebased off of master @lu-zero @barrbrain

2021-12-12 10:43 UTC, lu-zero approved these changes
Thank you a lot!

2021-12-12 18:51 UTC, merged