Add a release-nolto profile
xiph/rav1e pull request #2963
Opened 2022-07-14 09:05 UTC by lu-zero

Workaround for #2960, because of rust-lang/rust#98302

2022-07-14 09:08 UTC, Luni-4 requested changes
Just a simple change, looks fine to me, thank you!

2022-07-14 09:08 UTC, Luni-4 commented on Cargo.toml
> +[profile.release-nolto]
`[profile.release-no-lto]`

2022-07-14 09:09 UTC, Luni-4 approved these changes

2022-07-14 09:11 UTC, lu-zero commented on Cargo.toml
> +[profile.release-nolto]
Sure

2022-07-15 01:00 UTC, shssoichiro approved these changes

2022-07-15 06:17 UTC, merged